# vim: sw=2 sts=2 et syntax= :

param int @fgcolor 15
param int @char 248
param bool @harmenemy true
param bool @harmplayer true
param dir @movedir idle
param entity @ownerentity noentity

on state main {
  move @movedir else {
    if @harmplayer {
      send @movedir enemyshot self @movedir @ownerentity
    }
    if @harmenemy {
      send @movedir playershot self @movedir @ownerentity
    }
    send @movedir shot self @movedir @ownerentity
    die
  }
  sleep 1
}
